# Generated by Django 5.1.7 on 2025-04-09 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Latest_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mv_name', models.CharField(max_length=50)),
                ('mv_desc', models.TextField(blank=True)),
                ('mv_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieFiles.genre')),
            ],
        ),
    ]
