# Generated by Django 5.1.7 on 2025-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieFiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_movie',
            name='mv_genre',
        ),
        migrations.AddField(
            model_name='latest_movie',
            name='mv_genre',
            field=models.ManyToManyField(to='MovieFiles.genre'),
        ),
    ]
