# Generated by Django 5.1.7 on 2025-04-15 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieFiles', '0002_remove_latest_movie_mv_genre_latest_movie_mv_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_movie',
            name='mv_genre',
        ),
        migrations.AddField(
            model_name='latest_movie',
            name='mv_genres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieFiles.genre'),
        ),
    ]
