# Generated by Django 5.1.7 on 2025-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieFiles', '0003_remove_latest_movie_mv_genre_latest_movie_mv_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_movie',
            name='mv_image',
            field=models.ImageField(null=True, upload_to='uploads/image'),
        ),
    ]
