# Generated by Django 5.1.7 on 2025-04-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieFiles', '0004_latest_movie_mv_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_movie',
            name='mv_genres',
        ),
        migrations.AddField(
            model_name='latest_movie',
            name='mv_genres',
            field=models.ManyToManyField(related_name='movies', to='MovieFiles.genre'),
        ),
    ]
