# Generated by Django 5.1.7 on 2025-05-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieFiles', '0005_remove_latest_movie_mv_genres_latest_movie_mv_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_movie',
            name='mv_actors',
            field=models.CharField(blank=True, help_text='Enter words seperated by comma', max_length=500, null=True),
        ),
    ]
