# Generated by Django 5.1.7 on 2025-05-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieFiles', '0006_latest_movie_mv_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='latest_movie',
            name='mv_category',
            field=models.ManyToManyField(blank=True, related_name='mv_cat', to='MovieFiles.category'),
        ),
    ]
