# Generated by Django 5.1.7 on 2025-05-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieFiles', '0007_category_latest_movie_mv_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_movie',
            name='mv_category',
        ),
        migrations.AddField(
            model_name='latest_movie',
            name='mv_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieFiles.category'),
        ),
    ]
